name: EC2 Deployment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure SSH connection
        uses: appleboy/ssh-action@main
        with:
          host: "${{ secrets.EC2_INSTANCE_APPTEST_IP }}"
          username: 'ubuntu'
          private-key: "${{ secrets.SSH_PRIVATE_KEY }}"
      - name: Deploy to EC2
        uses: aws-actions/deploy-ec2@v1
        with:
          instance-ip: 'ec2-3-95-16-153.compute-1.amazonaws.com'
          role-arn: 'arn:aws:iam::471112994860:role/EC2-Deployment-Role'
          bucket-name: 'my-deployment-bucket'
          deploy-path: '/var/www/htdocs'